swagger: "2.0"
info:
  title: Post Management API
  version: "1.0"

tags:
  - post
summary: Create a new post
description: Create a new post in the system.
parameters:
  - in: header
    name: Authorization
    schema:
      type: string
    required: true
    description: The JWT token to authorize API requests. Format "Bearer {token}"
  - name: body
    in: body
    required: true
    schema:
      type: object
      properties:
        title:
          type: string
          example: "My Post"
        text:
          type: string
          example: "This is my post content."
        user_id:
          type: string
          example: "1"
responses:
  201:
    description: Post created successfully.
  400:
    description: Bad Request (e.g., invalid JSON or trying to create a post with an invalid user ID).
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Invalid user ID"

definitions:
  Post:
    type: object
    properties:
      id:
        type: string
        example: "123-456-789"
      title:
        type: string
        example: "My Post"
      text:
        type: string
        example: "This is my post content."
      user_id:
        type: string
        example: "1"
      created_at:
        type: string
        example: "2024-08-30T12:34:56.789Z"
      updated_at:
        type: string
        example: "2024-08-30T12:34:56.789Z"
