swagger: "2.0"
info:
  title: Post Management API
  version: "1.0"

tags:
  - post
summary: Update an existing post
description: Update the details of an existing post by its ID.
parameters:
  - in: header
    name: Authorization
    schema:
      type: string
    required: true
    description: The JWT token to authorize API requests. Format "Bearer {token}"
  - name: post_id
    in: path
    required: true
    type: string
    description: The ID of the post to update.
  - name: body
    in: body
    required: true
    schema:
      type: object
      properties:
        title:
          type: string
          example: "Updated Post Title"
        text:
          type: string
          example: "This is the updated content of the post."
responses:
  200:
    description: Post successfully updated
    schema:
      type: object
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: "Updated Post Title"
        text:
          type: string
          example: "This is the updated content of the post."
        user_id:
          type: string
          example: "1"
        created_at:
          type: string
          example: "2024-08-30T12:34:56.789Z"
        updated_at:
          type: string
          example: "2024-09-01T10:15:30.789Z"
  400:
    description: Bad Request (e.g., invalid JSON or missing required fields)
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Invalid request data"
  404:
    description: Post not found
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Post not found"
  500:
    description: Internal server error
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Internal server error"
