swagger: "2.0"
info:
  title: User Management API
  version: "1.0"

tags:
  - user
summary: Update a user's information
description: Update the details of a specific user.
parameters:
  - in: header
    name: Authorization
    schema:
      type: string
    required: true
    description: The JWT token to authorize API requests. Format "Bearer {token}"
  - name: body
    in: body
    required: true
    schema:
      type: object
      properties:
        first_name:
          type: string
          example: "John"
        last_name:
          type: string
          example: "Doe"
        password:
          type: string
          example: "newpassword"
responses:
  200:
    description: User successfully updated.
    schema:
      type: object
      properties:
        id:
          type: string
          example: "1"
        email:
          type: string
          example: "user@example.com"
        first_name:
          type: string
          example: "John"
        last_name:
          type: string
          example: "Doe"
        created_at:
          type: string
          example: "2024-08-30T12:34:56.789Z"
        updated_at:
          type: string
          example: "2024-08-30T12:34:56.789Z"
  400:
    description: Bad Request (e.g., invalid JSON or trying to update immutable fields).
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Not a JSON or attempting to update immutable fields"
  404:
    description: User not found.
    schema:
      type: object
      properties:
        message:
          type: string
          example: "User not found"
