swagger: "2.0"
info:
  title: Post Management API
  version: "1.0"
tags:
  - timer
summary: Get top 10 users with the highest max_time
description: Get the top 10 users with the highest max_time.

parameters:
  - in: header
    name: Authorization
    schema:
      type: string
    required: true
    description: The JWT token to authorize API requests. Format "Bearer {token}"

responses:
  200:
    description: Top 10 users with the highest max_time
    content:
      application/json:
        schema:
          type: array
          items:
            type: object
            properties:
              username:
                type: string
                description: The username of the user
              max_time:
                type: integer
                description: The max_time of the user
