swagger: "2.0"
info:
  title: Articles API
  version: "1.0"

tags:
  - Article
summary: Create a new article
description: Add a new article to the system.
parameters:
  - in: header
    name: Authorization
    schema:
      type: string
    required: true
    description: The JWT token to authorize API requests. Format "Bearer {token}"
  - in: body
    name: body
    description: Article object that needs to be added to the system
    required: true
    schema:
      type: object
      properties:
        title:
          type: string
          example: "New Article"
        content:
          type: string
          example: "This is the content of the new article."
        author:
          type: string
          example: "John Doe"
          description: The name of the author of the article
          required: false
responses:
  201:
    description: Article created successfully
  400:
    description: Bad Request (e.g., missing fields)
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Missing title or content"
  500:
    description: Internal server error
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Internal server error"

definitions:
  Article:
    type: object
    properties:
      id:
        type: string
        example: "123"
      title:
        type: string
        example: "New Article"
      content:
        type: string
        example: "This is the content of the new article."
      author:
        type: string
        example: "John Doe"
        description: The name of the author of the article
      created_at:
        type: string
        example: "2024-08-30T12:34:56.789Z"
      updated_at:
        type: string
        example: "2024-08-30T12:34:56.789Z"
