swagger: "2.0"
info:
  title: Articles API
  version: "1.0"

tags:
  - Article
summary: Delete an article
description: Remove a specific article from the system by its ID.
parameters:
  - in: header
    name: Authorization
    schema:
      type: string
    required: true
    description: The JWT token to authorize API requests. Format "Bearer {token}"
  - name: article_id
    in: path
    required: true
    type: string
    description: The ID of the article to delete.
responses:
  200:
    description: Article successfully deleted
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Article deleted"
  404:
    description: Article not found
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Article not found"
  500:
    description: Internal server error
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Internal server error"
