swagger: "2.0"
info:
  title: Articles API
  version: "1.0"
  description: "API documentation for the Articles API"

tags:
  - Article
summary: Get all articles with pagination
description: Retrieve a list of all articles .
parameters:
  - name: page
    in: query
    required: false
    type: integer
    description: The page number
  - name: per_page
    in: query
    required: false
    type: integer
    description: The number of articles per page
  - name: filter_type
    in: query
    required: false
    type: string
    description: The filter type for the articles (most_liked, newest, oldest)
  - name: user_id
    in: query
    required: false
    type: string
    description: The ID of the user
responses:
  200:
    description: A list of articles
    schema:
      type: array
      items:
        $ref: "#/definitions/Article"
  500:
    description: Internal server error
    schema:
      type: object
      properties:
        message:
          type: string
          example: "Internal server error"
definitions:
  Article:
    type: object
    properties:
      id:
        type: string
        example: "123"
      title:
        type: string
        example: "Sample Article"
      content:
        type: string
        example: "This is the content of the article."
      author:
        type: string
        example: "John Doe"
      created_at:
        type: string
        example: "2024-08-30T12:34:56.789Z"
      updated_at:
        type: string
        example: "2024-08-30T12:34:56.789Z"
